// The variables and lists below are there to set up the database. May have to change some of these. 

TODO Add date to the list of data that players need to check (if we consider it relevant) 


LIST articles = art1, art2, art3, art4, art5, art6, art7, art8, art9, art10, art11, art12, art13, art14, art15, art16, art17, art18, art19, art20, art21, art22, art23,  art24, art25,  art26,  art27, art28,  art29,  art30,  art31,  art32,  art33,  art34,  art35,  art36,  art37,  art38,  art39,  art40,  art41,  art42,  art43,  art44,  art45,  art46,  art47 //this list is the number of items in the database. New entry in the database means adding an item here.

// The function below is to print out the source of the article, to facilitate both the labels in the database and localization. 


TODO THE FUNCTION BELOW IS JUST FOR THE PURPOSES OF THE PROTOTYPE, IN THE UNITY VERSION, THIS SHOULD PLUG IN TO THE EXTERNAL DATABASE

=== function article_data(print_article, what)  // this function is actually the database 
{print_article:
    - art1:
        ~ return data (what, "Asesinato de un niño en Mocejón (Toledo) por un inmigrante", "newspaper", "El Hotel Pattaya de Mocejón, Toledo, localidad donde ha sido asesinado a puñaladas un niño de 11 años, está albergando en estos momentos cerca de 30 inmigrantes ilegales según confirman fuentes cercanas al hotel!! Los vecinos de Mocejón hablan: 'El pasado lunes 5 de Agosto llegaron al pueblo 50 africanos en un autobús que los dejó en el Hotel Pattaya. Somos menos de 5.000 personas y vivíamos tranquilos. Ahora hay violaciones, robos y el asesinato de este niño de 10 años'", news, false)
    - art2:
        ~ return data (what, "La Seguridad Social anuncia que va a retirar la incapacidad permanente a más de 1 millón de personas", "newspaper", "El anuncio de la Seguridad Social que no te va a gustar. Van a retirar la incapacidad permanente a más de 1 millón de personas. La Seguridad Social acaba de anunciar que va a retirar a más de 1 millón de personas la pensión que cobran por la incapacidad permanente. Javier Frade - 02/12/2023", news, false)
    - art3:
        ~return data (what, "La clase media paga ya más del 50% de su sueldo a Hacienda tras las 69 subidas de impuestos de Sánchez", "social", "La clase media paga ya más del 50% de su sueldo a Hacienda tras las 69 subidas de impuestos de Sánchez España es el país de Europa que más sube la presión fiscal desde 2019. Un contribuyente medio abona casi 15.500 euros en impuestos al año, según apunta el Instituto Juan de Mariana.", news, false)
    - art4:
        ~return data (what, "Durante 2024 se pagará hasta 1.000 euros más de IRPF", "social", "Es un contenido que circula desde 2022 debido a una reforma del Gobierno. El primer texto que nos llegó fue este que hace referencia a que el cambio se debe por las elecciones generales de 2023: 'Algunos de ustedes habrán escuchado que para el año que viene el IRPF va a ser más bajo, pero quisiera leer darles de que esto es una trampa. Lo que se va a hacer es, en año electoral, reducir las retenciones de la empresa del IRPF. Es decir, usted va a tener más dinero en el bolsillo, pero porque va a pagar menos a través de la empresa.'", news, false)
    - art5:
        ~return data (what, "Arotz González Gorka, marido de Marlaska, es titular de una cuenta con ingresos anómalos", "social", "ENTIDAD: CITIBANAMEX DIRECCION: CONTRATO/TIPO: CONDICIONES: IDENTIFICACION: OP MONTERREY DEPOSITO A PLAZO RENOVACION AUTOMATICA 24 MESES 3567434 17/12/2018 INICIO: ESTADO: IMPORTE: TITULAR: VIGENTE 600.000$ AROTZ GONZALEZ GORKA (DESDE 17/01/2019) BANCO DOMICILIO: citibanamex VIS @Alvisepf&nbsp; Se llama Arotz González Gorka. Consta como titular de una cuenta bancaria en la entidad 'Citibanamex' de Monterrey con 40 ingresos anómalos de 600.000 euros", news, false)
     - art6:
        ~ return data (what, "Luchadora que vence a otras mujeres en este vídeo es trans", "social", "La ley trans puede desigualar mucho el deporte femenino. Me importa un bledo lo que diga @IreneMontero o cualquier alimaña de su ministerio @IgualdadGob, ninguna mujer de mi familia va a competir con personas trans, no es igualdad de condiciones y así me lo han comunicado", news, false)
    - art7:
        ~return data (what, "Dos terceras partes de la población respiraron aire contaminado en 2024", "newspaper", "Un total de 31 millones de personas en España —dos terceras partes de la población— estuvieron expuestas durante 2024 a unos niveles de contaminación que exceden los nuevos límites aprobados para 2030 por la Unión Europea (UE), según Ecologistas en Acción. Aún así, la calidad del aire en España mejoró respecto a 2023 y los años anteriores a la pandemia de Covid-19 y un factor «esencial» para explicarlo es la evolución reciente del sistema energético.", science, true)
    - art8:
        ~return data (what, "El cambio climático no está causado por las actividades humanas, son ciclos naturales", "social", "La NASA admite que el cambio climático ocurre por la órbita de la Tierra alrededor del Sol y no por los combustibles fósiles.", science, false)
    - art9:
        ~return data (what, "Un coche eléctrico explota en Milán", "social", "Milán. Un coche eléctrico se incendia en la calle. Son un peligro y un fiasco. El fin de este circo, desde el golpe de la gobernanza mundial kovi 2020, es la transformación de hábitos y el incremento totalitario de control político, con los sociópatas amparados en 'portubien'.", science, true)
    - art10:
        ~return data (what, "26 presas se demolieron en Valencia entre 2020 y 2024 son causa de la DANA.", "social", "Todos los expertos coinciden. Las 26 presas que se demolieron en Valencia entre 2020 y 2024 son la causa de la catástrofe vivida que ocasiono enormes perdidas humanas y materiales. ", conspiracy, false)
    - art11:
        ~return data (what, "Casos de miocarditis y pericarditis con la vacuna contra la COVID-19 de Pfizer", "social", "La OMS estudia posibles problemas de corazón tras recibir la vacuna de Pfizer COVID - 19.", science, false)
    - art12:
        ~return data (what, "No, este correo electrónico que te avisa de 'irregularidades en su declaración de la renta' no es de la Agencia Tributaria: es phishing.", "social", "Se han detectado irregularidades en su reciente declaración de la Renta. En caso de no realizar el pago en fecha puede incurrir en cargos y multas extras. Pinche AQUÍ pare ver la factura con la deferencia que debe abonar y realizar el pago.", scam, true)
    - art13:
         ~return data (what, "Los aviones tiran petardos con yoduro de plata para impedir la lluvia", "social", "Estos petardos son 'yoduro de plata'. Los echan por encima de las nubes y no cae ni gota. Son tóxicos y cambian el clima. Nos están envenenando. ", science, false)
    - art14:
        ~return data (what, "HEADLINE 14", "social", "Paragraph 14", scam, true)
    - art15:
        ~return data (what, "Fraude masivo suplantando a Lidl con falsos descuentos online", "blog", "Se puso en contacto con la Línea de Ayuda en Ciberseguridad de INCIBE, través del teléfono gratuito y confidencial 017, un usuario que señalaba que tras la búsqueda de un sofá en Internet, detectó que los primeros resultados del motor de búsqueda incluían enlaces a páginas web con ofertas a precios inusualmente bajos.", scam, true)
    - art16:
        ~return data (what, "Banco Santander: Usuario deshabilitado por razones de seguridad", "social", "Paragraph 16", scam, false)
    - art17:
        ~return data (what, "Valencia ha sido producto de un ataque meteorológico HAARP", "social", "Paragraph 17", conspiracy, false)
    - art18:
        ~return data (what, "El Rey Felipe VI ha puesto en marcha una innovadora plataforma al alcance de todos", "social", "Hola, soy el rey Felipe, y te presento una plataforma nueva de inversión fácil. Todo lo que tienes que hacer es registrarte a través del enlace y realizar una única inversión de 250 euros. Si no ganáis 5.000 euros en vuestra primera semana en la plataforma, os pagaré a cada uno 50.000 euros en concepto de indemnización. Solo los valientes tendrán éxito! Beneficio mensual Más información FORMAS DE PAGO VISA MasterCard INSCRIPCIÓN", scam, false)     
    - art19:
        ~return data (what, "Los alimentos con el símbolo de la rana de Rainforest Alliance tienen insectos molidos", "social", "Erdo hoy a las 13:35 9 de 10 El sello de la rana corresponde a la certificación Rainforest Alliance, este sello va en el etiquetado o enlatado de los alimentos. Si lo llevan significa que ese producto lleva toda clase de insectos Detrás de esto está Bill Gates. CERTIFIED Esto es una de las cosas que entran en la Agenda20-30. Aprobado por la UE. Las marcas más conocidas, de harinas, Chocolates, Cereales... Ya llevan insectos molidos. Comparte. X80 CROSSED MOR", conspiracy, true)
    - art20:
        ~return data (what, "Los pájaros no existen", "social", "Los pájaros no son reales. Los pájaros en realidad son drones de alta tecnología con aspecto de palomas que están hechos para espiarnos a todos. Se recargan cuando se posan en los cables eléctricos, y los excrementos son líquidos con nanorobots que permiten el seguimiento de vehículos y personas. El gobierno nos está ENGAÑANDO. ¡DESPERTAD!", conspiracy, false)
    - art21:
        ~return data (what, "El Foro Económico Mundial ordena quemar a las abejas para provocar una hambruna mundial", "social", "WEF ordena a los gobiernos quemar abejas para provocar una 'hambruna global' 🤔 ... a ver qué tienen que decir sobre esto los que son supostos protectores de la naturaleza ? EI FEM ordena al gobierno quemar millones de abejas para provocar una 'hambruna global' Los apicultores de todo el mundo informan que funcionarios gubernamentales visitan granjas destruyen colonias de abejas sanas sin motivo alguno y sin realizar pruebas para detectar las", conspiracy, false)
    - art22:
        ~return data (what, "Nos fumigan con chemtrails - varias fotos de aviones con esta narrativa", "social", "Los chemtrails nos envenenan. Una nube tóxica sobrevuela Sicilia y eso evita las lluvias. Esto es la verdadera causa del cambio climático, que en realidad es un invento para subirnos los impuestos.", conspiracy, false)
    - art23:
        ~return data (what, "La mujer de Pedro Sánchez, Begoña Gómez, es un travesti", "social", "La mujer del presidente es un travesti es un travesti y al más que tú lo puedes comprobar vete a Google pide fotografía de Begoña Gómez", conspiracy, false)
    - art24:
        ~return data (what, "Han suspendido a un médico por cantar Soy Minero antes de las colonoscopias", "social", "Fuerte conmoción existente en el Hospital de Valdecilla después de que se conociera que un destacado médico gastroneterólogo fuera suspendido de empleo y sueldo tras confirmarse que cantaba la canción ‘Soy minero’ delante de sus pacientes antes de realizarles una colonoscopia. El acusado de cantar la famosa canción de Antonio Molina ha reconocido los hechos después de que un paciente de 49 años consiguiera grabarle mientras gritaba “Soy minero y temple mi corazón con pico y barrena, soy minero y con caña vino y ron me quito las penas” mientras le abría el ano sin ningún tipo tacto. Según se ha podido demostrar a raíz de la primera demanda, no sería la única vez que este médico habría cantado la cancioncita de los cojones. Por este motivo y para callar a la prensa de las acusaciones el Hospital de Valdecilla ha decidido suspenderle de empleo y sueldo durante 12 meses hasta que pase la “tormenta”.", news, true) 
    - art25:
        ~return data (what, "Se anuncian recortes en las pensiones de los nacidos entre 1950 y 1970", "social", "El ministro de Inclusión, Seguridad Social y Migraciones anuncia un recorte de las pensiones de los nacidos entre 1950 y 1970. Esta parte de la población podrían elegir probablemente entre distintas opciones: un ajuste en su pensión o alternativamente trabajar algo más.", news, false)
    - art26:
        ~return data (what, "Un adulto llevando a cuestas a cinco niños heridos en Palestina", "social", "Un adulto llevando a cuestas a cinco niños heridos en Palestina Imágenes que llegan de Gaza. Deberían llamarle héroe!!!", computers, false)
    - art27:
        ~return data (what, "El gran dictador", "social", "Se habla mucho de si Franco fue un dictador o no. Franco dictó grandes leyes: creó la Seguridad Social y la pensión por jubilación, estableció la edad obligatoria de jubilación, creó escuelas PÚBLICAS Y GRATUITAS, universidades, y escuelas de educación superior. Bajo su mandato, se crearon 4,5 millones de viviendas de protección social, y se construyeron pantanos para abastecer de energía y agua potable. También dicto 3 pagas extras, vacaciones pagadas, baja laboral, descanso dominical, y la ley de subsidio de desempleo. Y así muchas más cosas. Queda demostrado que fue un GRAN DICTADOR. ", news, false)
    - art28:
        ~return data (what, "Hacienda ingresa 566 millones por el nuevo impuesto a la banca en el primer pago del año", "newspaper", "El nuevo impuesto que afecta a las entidades financieras y de crédito, aprobado por el Congreso en una votación agónica que tuvo lugar a finales de 2024, ha dejado ya su primer ingreso en las arcas públicas. Según recoge el último informe mensual de recaudación, correspondiente al mes de junio y publicado este jueves por la Agencia Tributaria, el gravamen ha generado en su primer pago fraccionado un total de 566 millones de euros.", news, true) 
    - art29:
        ~return data (what, "Inspectores de Hacienda ven “imposible” aplicar el acuerdo de financiación catalana", "newspaper", "La Asociación de Inspectores de Hacienda del Estado (IHE) ha señalado este miércoles que es “imposible” aplicar el acuerdo de financiación singular alcanzado entre el Ejecutivo central y la Generalitat catalana, un pacto que, bajo su punto de vista, supone el principio de la “desaparición del Estado” si se extiende al resto de comunidades autónomas. Al mismo tiempo, la asociación que reúne a los funcionarios del cuerpo de élite de la Agencia Tributaria ha vuelto a exigir la dimisión de la ministra de Hacienda, María Jesús Montero.", news, true)   
    - art30:
        ~return data (what, "La Casa Blanca se burla de un inmigrante deportado convirtiéndolo en una parodia en redes sociales", "newspaper", "La Casa Blanca publicó en la noche del lunes en sus redes sociales, tanto en Instagram como en X, una imagen creada por inteligencia artificial en la que aparece una caja a imitación de las de los muñecos Labubu y, dentro, el dibujo de un hombre esposado junto a esta frase: “Depredador sexual extranjero ilegal arrestado por el ICE. ¡Deportado!”.", news, true)  
    - art31:
        ~return data (what, "Canarias ha recibido 106 menores en un día, mientras solo han salido 30 en estos meses hacia Península", "newspaper", "El portavoz del Gobierno de Canarias, Alfonso Cabello, ha denunciado que apenas unos 30 menores migrantes no acompañados con derecho a asilo han salido de las islas, mientras siguen llegando menores en cayucos y pateras al archipiélago en un número muy superior. Solo este domingo llegaron otros 106 menores de 18 años a Gran Canaria.", news, true)
    - art32:
        ~return data (what, "Matrimonio simulado: se casan en Granada para obtener la residencia y los novios, el padre de ella y dos testigos acaban detenidos", "newspaper", "El hombre, marroquí, intentó lograr un permiso de residencia por arraigo y para ello quien iba a ser su suegro lo empadronó en su casa aunque nunca vivió en ella.", news, true)
    - art33:
        ~return data (what, "Descubren en Granada un matrimonio simulado para regularizar a una marroquí a cambio de ser una «esclava sexual»", "newspaper", "Agentes de la Policía Nacional han detenido en Granada a tres hombres y una mujer, con edades comprendidas entre los 23 y 79 años, como presuntos responsables intentar regularizar a una marroquí trayéndola a España mediante un matrimonio simulado y ofreciéndola como esclava sexual a la persona que se hacía cargo de los gastos.", news, true)
    - art34:
        ~return data (what, "Los niños invisibles: decenas de miles de menores viven durante años en la clandestinidad por no tener papeles", "newspaper", "Aunque los menores extranjeros no acompañados que llegan a las costas españolas en pateras o en cayucos son quienes suelen ocupar los titulares en la prensa, la gran mayoría de los menores migrantes están en España junto a sus familias y han llegado a bordo de un avión. Pero parte de ellos, aún cuando sus padres consiguen los papeles, están obligados a permanecer en la clandestinidad hasta que sus progenitores logran regularizarlos a través de la reagrupación familiar, que exige ciertos requisitos económicos y de alojamiento, aunque los menores ya estén en España.", news, true)
    - art35:
        ~return data (what, "Un gran estudio confirma la relación entre seguir una dieta respetuosa con el planeta y una menor mortalidad", "newspaper", "Un metaanálisis publicado este viernes en la revista Science Advances ha relacionado el llevar una dieta planetaria saludable (PHD por sus siglas en inglés) con un menor riesgo de mortalidad por cáncer y enfermedades cardiovasculares. También reduciría el riesgo de sufrir cáncer colorrectal, cáncer de pulmón, enfermedades coronarias, accidentes cerebrovasculares y diabetes. El análisis se hizo utilizando dos cohortes con más de 150.000 personas y un metaanálisis de 37 trabajos previos con más de tres millones de voluntarios, lo que lo convierte en uno de los más amplios jamás publicados en este campo.", science, true)
    - art36:
        ~return data (what, "Una investigación revela cómo la contaminación puede desencadenar cambios dañinos en el cerebro que llevan a la neurodegeneración", "newspaper", "Una nueva investigación, publicada este jueves en la revista Science, se ha centrado en el nexo entre la contaminación atmosférica y el riesgo de desarrollar demencias, un grupo de dolencias neurodegenerativas tradicionalmente asociadas al envejecimiento y que se caracterizan por destruir la memoria y la autonomía del individuo.", science, true)
    - art37:
        ~return data (what, "Abusar de los edulcorantes podría acelerar el deterioro cognitivo", "newspaper", "Un nuevo estudio publicado en la revista Neurology asocia el consumo de algunos de estos edulcorantes con un deterioro cognitivo más rápido.", science, true)
    - art38:
        ~return data (what, "La IA logra que una persona con paraplejia controle un brazo robótico con sus pensamientos", "newspaper", "En el estudio, publicado en 'Nature Machine Intelligence', una persona con paraplejia logró controlar un cursor en pantalla casi cuatro veces mejor gracias al apoyo de algoritmos de IA. Además, pudo completar tareas con un brazo robótico que resultaban imposibles sin esta ayuda.", computers, true)
    - art39:
        ~return data (what, "El ibuprofeno y el paracetamol fomentan la resistencia a los antibióticos, según un estudio", "newspaper", "Una nueva investigación de la Universidad de Australia Meridional (Australia), publicada en 'npj Antimicrobials and Resistance', muestra que medicamentos como el ibuprofeno y el paracetamol están alimentando silenciosamente una de las mayores amenazas para la salud en el mundo: la resistencia a los antibióticos. En el primer estudio de este tipo, los investigadores descubrieron que el ibuprofeno y el paracetamol no solo fomentan la resistencia a los antibióticos cuando se utilizan por separado, sino que la amplifican cuando se utilizan juntos.", science, true)
    - art40:
        ~return data (what, "Detectan retrasos del desarrollo cerebral en niños infectados por la covid en el embarazo", "newspaper", "Las niñas y niños de 5 años que contrajeron el virus de la covid-19 en el embarazo de sus madres (de forma congénita) y antes de las primeras vacunas de la pandemia presentan un aumento del 10 por ciento en los casos de retraso del desarrollo cognitivo, principalmente en los campos del aprendizaje y la memoria. Esta es la principal conclusión de una novedosa investigación sobre los efectos de la pandemia del virus SARS-CoV-2 durante el estado de gestación, que ha sido liderada por el Instituto de Neurociencias del CSIC", science, true)
    - art41:
        ~return data (what, "Un estudio apuntala el vínculo del cambio climático con la histórica ola de incendios de agosto", "newspaper", "Un grupo de investigadores concluye que el calentamiento hace 40 veces más probable que se den las condiciones meteorológicas que favorecieron los fuegos del noroeste de España.", science, true)
    - art42:
        ~return data (what, "El calor no solo mata de día: las noches tropicales elevan la mortalidad", "newspaper", "Dos investigaciones del Instituto de Salud Carlos III y el CSIC revelan el impacto negativo de las altas temperaturas nocturnas en la salud y apuntan a la necesidad de extender los planes de prevención.", science, true)
    - art43:
        ~return data (what, "La Aemet confirma que la última ola de calor ha sido la más intensa desde que hay registros, con una anomalía de 4,6 grados", "newspaper", "La ola de calor sufrida en España entre los pasados 3 y 18 de agosto fue la más intensa desde que hay registros, en concreto, desde 1975. Durante la misma se registraron los diez días seguidos más cálidos desde al menos 1950 y este verano se perfila ya como uno de los dos más cálidos de la serie histórica, empatando con el de 2022, que tiene el récord.", science, true)
    - art44:
       ~return data (what, "¿Qué riesgo tiene dar nuestros datos personales por Internet?", "newspaper", "Al navegar por Internet, debemos hacer algo simple y complicado a la vez: ser muy precavidos a la hora de facilitar nuestros datos, como, por ejemplo, nuestro código postal.También deberíamos activar un mínimo de dos factores de identificación ante cualquier operación, aunque a veces nos parezca un tanto pesado o fastidioso. Y tampoco podemos olvidar activar antivirus y cualquier otro programa que pueda detectar y bloquear amenazas antes de que nos ataquen. Si, por último, no hemos logrado evitar la estafa, podemos comunicar cualquier intento de fraude a la Línea de Ayuda de Ciberseguridad que ofrece el INCIBE (Instituto Nacional de Ciberseguridad de España).", scam, true)
    - art45:
        ~return data (what, "¿Qué riesgo tiene dar nuestros datos personales por Internet?", "newspaper", "Al navegar por Internet, debemos hacer algo simple y complicado a la vez: ser muy precavidos a la hora de facilitar nuestros datos, como, por ejemplo, nuestro código postal.También deberíamos activar un mínimo de dos factores de identificación ante cualquier operación, aunque a veces nos parezca un tanto pesado o fastidioso. Y tampoco podemos olvidar activar antivirus y cualquier otro programa que pueda detectar y bloquear amenazas antes de que nos ataquen. Si, por último, no hemos logrado evitar la estafa, podemos comunicar cualquier intento de fraude a la Línea de Ayuda de Ciberseguridad que ofrece el INCIBE (Instituto Nacional de Ciberseguridad de España).", scam, true)
    - art46:
        ~return data (what, "La DGT alerta de una nueva estafa: cuidado si recibes este SMS con una supuesta multa", "newspaper", "La Dirección General de Tráfico (DGT) ha detectado una nueva oleada de smishing, una técnica utilizada por los ciberdelincuentes para suplantar a entidades legítimas mediante el envío de un SMS. En este caso, algunos ciudadanos están recibiendo un mensaje de texto para pagar una supuesta multa pendiente. Pero es un fraude y no hay que clicar, recuerda Tráfico en una publicación de X (antes Twitter).", scam, true)
    - art47:
        ~return data (what, "Nuevo método para robar cuentas de WhatsApp a través de videollamada", "blog", "Se puso en contacto con la Línea de Ayuda de Ciberseguridad de INCIBE a través del teléfono gratuito y confidencial 017, un usuario buscando asesoramiento sobre lo que le había ocurrido. Nos informó que había perdido el control de su cuenta de WhatsApp tras recibir una videollamada de un contacto en la que solo se veía oscuridad, al comentárselo este le indicó que tenía un problema con el dispositivo y que compartiese pantalla para comprobar si así funcionaba. En ese momento recibió una notificación en la parte superior de la pantalla, tratándose de un SMS de WhatsApp con su código de seguridad. Al estar compartiendo pantalla, este código fue visible para su interlocutor. Inmediatamente después se cerró la aplicación, siendo imposible volver a acceder. En las siguientes horas, algunos de sus contactos le informaron que estaban recibiendo mensajes desde su cuenta de WhatsApp solicitándoles dinero a través de Bizum de manera urgente. Y otros solicitándoles un código que acababan de recibir a través de SMS.", scam, true)
    - else: [No se encuentra {print_article}]

    }
    


